import { ParsedSummary } from "./parse-summary";

function slugify(title: string) {
  return title.replace(/[^a-z0-9]/gi, "_");
}

function triggerDownload(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsTxt(
  parsed: ParsedSummary,
  fileName: string,
  createdAt: string
) {
  const lines = [
    parsed.title.toUpperCase(),
    `Generated on: ${new Date(createdAt).toLocaleDateString()} · ${parsed.readTime}`,
    "",
    "OVERVIEW",
    "────────────────────────────────────────",
    parsed.overview,
    "",
    "KEY POINTS",
    "────────────────────────────────────────",
    ...parsed.keyPoints.map((p, i) => `${i + 1}. ${p}`),
    "",
    "SECTIONS",
    "────────────────────────────────────────",
    ...parsed.sections.flatMap((s) => [
      `▶ ${s.title}`,
      ...s.points.map((p) => `   ${p}`),
      "",
    ]),
    "KEY TAKEAWAYS",
    "────────────────────────────────────────",
    ...parsed.actionItems.map((a) => `→ ${a}`),
    "",
    "────────────────────────────────────────",
    `Original File: ${fileName}`,
    "Generated by Summarist AI",
  ];

  triggerDownload(
    new Blob([lines.join("\n")], { type: "text/plain" }),
    `Summary-${slugify(parsed.title)}.txt`
  );
}

export function exportAsMarkdown(
  parsed: ParsedSummary,
  fileName: string,
  createdAt: string
) {
  const lines = [
    `# ${parsed.title}`,
    `> Generated on: ${new Date(createdAt).toLocaleDateString()} · ${parsed.readTime}`,
    "",
    "## Overview",
    parsed.overview,
    "",
    "## Key Points",
    ...parsed.keyPoints.map((p) => `- ${p}`),
    "",
    "## Sections",
    ...parsed.sections.flatMap((s) => [`### ${s.title}`, ...s.points, ""]),
    "## Key Takeaways",
    ...parsed.actionItems.map((a) => `- ${a}`),
    "",
    "---",
    `*Original File: ${fileName} — Generated by Summarist AI*`,
  ];

  triggerDownload(
    new Blob([lines.join("\n")], { type: "text/markdown" }),
    `Summary-${slugify(parsed.title)}.md`
  );
}

export function exportAsDoc(
  parsed: ParsedSummary,
  fileName: string,
  createdAt: string
) {
  const keyPointsHtml = parsed.keyPoints.map((p) => `<li>${p}</li>`).join("");

  const sectionsHtml = parsed.sections
    .map(
      (s) =>
        `<h3 style="color:#111;">${s.title}</h3>${s.points.map((p) => `<p>${p}</p>`).join("")}`
    )
    .join("");

  const actionItemsHtml = parsed.actionItems
    .map((a) => `<li>${a}</li>`)
    .join("");

  const html = `
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Calibri, Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #222; line-height: 1.6; }
    h1 { font-size: 26px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    h3 { font-size: 15px; margin-top: 16px; }
    p, li { font-size: 14px; }
    .meta { color: #777; font-size: 13px; margin-bottom: 24px; }
    footer { margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>${parsed.title}</h1>
  <p class="meta">Generated on: ${new Date(createdAt).toLocaleDateString()} &nbsp;·&nbsp; ${parsed.readTime}</p>

  <h2>Overview</h2>
  <p>${parsed.overview}</p>

  <h2>Key Points</h2>
  <ol>${keyPointsHtml}</ol>

  <h2>Sections</h2>
  ${sectionsHtml}

  <h2>Key Takeaways</h2>
  <ul>${actionItemsHtml}</ul>

  <footer>Original File: ${fileName} — Generated by Summarist AI</footer>
</body>
</html>`;

  triggerDownload(
    new Blob([html], { type: "application/msword" }),
    `Summary-${slugify(parsed.title)}.doc`
  );
}
