export const plans = [
  {
    id: "free",
    name: "Free",
    subtitle: "Get started",
    price: 0,
    period: "forever",
    features: [
      "2 PDF summaries / month",
      "2 PDF chats / month",
      "Standard processing",
      "Email support",
    ],
    buttonText: "Start Free",
    popular: false,
    accent: false,
    productId: null,
  },
  {
    id: "pro",
    name: "Pro",
    subtitle: "For power users",
    price: 5,
    period: "month",
    features: [
      "10 PDF summaries / month",
      "10 PDF chats / month",
      "Priority processing",
      "24/7 priority support",
      "Markdown export",
      "Docs export",
    ],
    buttonText: "Go Pro",
    popular: true,
    accent: true,
    productId: "pro",
  },
  {
    id: "unlimited",
    name: "Unlimited",
    subtitle: "No limits, ever",
    price: 20,
    period: "month",
    features: [
      "Unlimited PDF summaries",
      "Unlimited PDF chats",
      "Priority processing",
      "24/7 priority support",
      "Markdown export",
      "Docs export",
    ],
    buttonText: "Go Unlimited",
    popular: false,
    accent: false,
    productId: "unlimited",
  },
];
