"use client";
import React from "react";

import { Download } from "lucide-react";

import { Button } from "@/components/ui/button";

const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
        
${summaryText}
        
Original File: ${fileName}
Generated by Summarist.AI`;

    const blob = new Blob([summaryContent], {
      type: "text/plain",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.text`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      className="h-8 bg-rose-100 px-3 text-rose-600 hover:bg-rose-50 hover:text-rose-700"
      size={"sm"}
      onClick={handleDownload}
    >
      <Download className="mr-1 h-4 w-4" />
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
